var data2 = [
  {
    category: '세부공종',
    item: '품목',
    specification: '규격',
    unit: '단위',
    revision: '변경 차수',
    contract_quantity: '도급내역',
    plan_quantity: '실행예정',
    execution_quantity: '시행내역',
    adjustment_quantity: '정산내역',
    remark: '비고1',
  },
  {
    contract_quantity: '수량',
    contract_material_unit: '직접재료비',
    contract_labor_unit: '직접노무비',
    contract_equipment_unit: '기계경비',
    contract_total_unit: '합계',
    plan_quantity: '수량',
    plan_material_unit: '직접재료비',
    plan_labor_unit: '직접노무비',
    plan_equipment_unit: '기계경비',
    plan_total_unit: '합계',
    execution_quantity: '수량',
    execution_material_unit: '직접재료비',
    execution_labor_unit: '직접노무비',
    execution_equipment_unit: '기계경비',
    execution_total_unit: '합계',
    adjustment_quantity: '수량',
    adjustment_material_unit: '직접재료비',
    adjustment_labor_unit: '직접노무비',
    adjustment_equipment_unit: '기계경비',
    adjustemnt_total_unit: '합계',
  },
  {
    contract_material_unit: '단가',
    contract_material_total: '금액',
    contract_labor_unit: '단가',
    contract_labor_total: '금액',
    contract_equipment_unit: '단가',
    contract_equipment_total: '금액',
    contract_total_unit: '단가',
    contract_total_total: '금액',
    plan_material_unit: '단가',
    plan_material_total: '금액',
    plan_labor_unit: '단가',
    plan_labor_total: '금액',
    plan_equipment_unit: '단가',
    plan_equipment_total: '금액',
    plan_total_unit: '단가',
    plan_total_total: '금액',
    execution_material_unit: '단가',
    execution_material_total: '금액',
    execution_labor_unit: '단가',
    execution_labor_total: '금액',
    execution_equipment_unit: '단가',
    execution_equipment_total: '금액',
    execution_total_unit: '단가',
    execution_total_total: '금액',
    adjustment_material_unit: '단가',
    adjustment_material_total: '금액',
    adjustment_labor_unit: '단가',
    adjustment_labor_total: '금액',
    adjustment_equipment_unit: '단가',
    adjustment_equipment_total: '금액',
    adjustment_total_unit: '단가',
    adjustment_total_total: '금액',
  },
  {
    category: '건축 > 공통가설공사',
    item: '조립식가설사무소 / 도급자용,감독,감리자용',
    specification: '15개월',
    unit: 'M2',
    revision_cnt: 0,
    revision: '최초',
    contract_quantity: 240,
    contract_material_unit: 141150,
    contract_material_total: '=F4*G4',
    contract_labor_unit: 0,
    contract_labor_total: '=F4*I4',
    contract_equipment_unit: 0,
    contract_equipment_total: '=F4*K4',
    contract_total_unit: '=G4+I4+K4',
    contract_total_total: '=H4+J4+L4',
    plan_quantity: 240,
    plan_material_unit: 114463,
    plan_material_total: '=O4*P4',
    plan_labor_unit: 0,
    plan_labor_total: '=O4*R4',
    plan_equipment_unit: 0,
    plan_equipment_total: '=O4*T4',
    plan_total_unit: '=P4+R4+T4',
    plan_total_total: '=Q4+S4+U4',
    execution_quantity: 240,
    execution_material_unit: 114463,
    execution_material_total: '=X4*Y4',
    execution_labor_unit: 0,
    execution_labor_total: '=X4*AA4',
    execution_equipment_unit: 0,
    execution_equipment_total: '=X4*AC4',
    execution_total_unit: '=Y4+AA4+AC4',
    execution_total_total: '=Z4+AB4+AD4',
    adjustment_quantity: 240,
    adjustment_material_unit: 114463,
    adjustment_material_total: '=AG4*AH4',
    adjustment_labor_unit: 0,
    adjustment_labor_total: '=AG4*AJ4',
    adjustment_equipment_unit: 0,
    adjustment_equipment_total: '=AG4*AL4',
    adjustment_total_unit: '=AH4+AJ4+AL4',
    adjustment_total_total: '=AI4+AK4+AM4',
    remark: '비고',
  },
  {
    item: '조립식가설사무소 / 도급자용,감독,감리자용',
    specification: '15개월',
    unit: 'M2',
    revision_cnt: 1,
    revision: '1차변경',
    contract_quantity: 240,
    contract_material_unit: 141150,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 240,
    plan_material_unit: 114463,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 240,
    execution_material_unit: 114463,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 240,
    adjustment_material_unit: 114463,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F5*G5',
    contract_labor_total: '=F5*I5',
    contract_equipment_total: '=F5*K5',
    contract_total_unit: '=G5+I5+K5',
    contract_total_total: '=H5+J5+L5',
    plan_material_total: '=O5*P5',
    plan_labor_total: '=O5*R5',
    plan_equipment_total: '=O5*T5',
    plan_total_unit: '=P5+R5+T5',
    plan_total_total: '=Q5+S5+U5',
    execution_material_total: '=X5*Y5',
    execution_labor_total: '=X5*AA5',
    execution_equipment_total: '=X5*AC5',
    execution_total_unit: '=Y5+AA5+AC5',
    execution_total_total: '=Z5+AB5+AD5',
    adjustment_material_total: '=AG5*AH5',
    adjustment_labor_total: '=AG5*AJ5',
    adjustment_equipment_total: '=AG5*AL5',
    adjustment_total_unit: '=AH5+AJ5+AL5',
    adjustment_total_total: '=AI5+AK5+AM5',
    remark: '',
  },
  {
    item: '조립식가설창고 / 도급자용',
    specification: '15개월',
    unit: 'M2',
    revision_cnt: 0,
    revision: '최초',
    contract_quantity: 70,
    contract_material_unit: 102115,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 70,
    plan_material_unit: 82808,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 70,
    execution_material_unit: 82808,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 70,
    adjustment_material_unit: 82808,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F6*G6',
    contract_labor_total: '=F6*I6',
    contract_equipment_total: '=F6*K6',
    contract_total_unit: '=G6+I6+K6',
    contract_total_total: '=H6+J6+L6',
    plan_material_total: '=O6*P6',
    plan_labor_total: '=O6*R6',
    plan_equipment_total: '=O6*T6',
    plan_total_unit: '=P6+R6+T6',
    plan_total_total: '=Q6+S6+U6',
    execution_material_total: '=X6*Y6',
    execution_labor_total: '=X6*AA6',
    execution_equipment_total: '=X6*AC6',
    execution_total_unit: '=Y6+AA6+AC6',
    execution_total_total: '=Z6+AB6+AD6',
    adjustment_material_total: '=AG6*AH6',
    adjustment_labor_total: '=AG6*AJ6',
    adjustment_equipment_total: '=AG6*AL6',
    adjustment_total_unit: '=AH6+AJ6+AL6',
    adjustment_total_total: '=AI6+AK6+AM6',
    remark: '',
  },
  {
    item: '조립식가설창고 / 도급자용',
    specification: '15개월',
    unit: 'M2',
    revision_cnt: 1,
    revision: '1차변경',
    contract_quantity: 70,
    contract_material_unit: 102115,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 70,
    plan_material_unit: 82808,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 70,
    execution_material_unit: 82808,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 70,
    adjustment_material_unit: 82808,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F7*G7',
    contract_labor_total: '=F7*I7',
    contract_equipment_total: '=F7*K7',
    contract_total_unit: '=G7+I7+K7',
    contract_total_total: '=H7+J7+L7',
    plan_material_total: '=O7*P7',
    plan_labor_total: '=O7*R7',
    plan_equipment_total: '=O7*T7',
    plan_total_unit: '=P7+R7+T7',
    plan_total_total: '=Q7+S7+U7',
    execution_material_total: '=X7*Y7',
    execution_labor_total: '=X7*AA7',
    execution_equipment_total: '=X7*AC7',
    execution_total_unit: '=Y7+AA7+AC7',
    execution_total_total: '=Z7+AB7+AD7',
    adjustment_material_total: '=AG7*AH7',
    adjustment_labor_total: '=AG7*AJ7',
    adjustment_equipment_total: '=AG7*AL7',
    adjustment_total_unit: '=AH7+AJ7+AL7',
    adjustment_total_total: '=AI7+AK7+AM7',
    remark: '',
  },
  {
    item: '조립식가설실험실',
    specification: '15개월',
    unit: 'M2',
    revision_cnt: 0,
    revision: '최초',
    contract_quantity: 20,
    contract_material_unit: 76302,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 20,
    plan_material_unit: 61876,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 20,
    execution_material_unit: 61876,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 20,
    adjustment_material_unit: 61876,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F8*G8',
    contract_labor_total: '=F8*I8',
    contract_equipment_total: '=F8*K8',
    contract_total_unit: '=G8+I8+K8',
    contract_total_total: '=H8+J8+L8',
    plan_material_total: '=O8*P8',
    plan_labor_total: '=O8*R8',
    plan_equipment_total: '=O8*T8',
    plan_total_unit: '=P8+R8+T8',
    plan_total_total: '=Q8+S8+U8',
    execution_material_total: '=X8*Y8',
    execution_labor_total: '=X8*AA8',
    execution_equipment_total: '=X8*AC8',
    execution_total_unit: '=Y8+AA8+AC8',
    execution_total_total: '=Z8+AB8+AD8',
    adjustment_material_total: '=AG8*AH8',
    adjustment_labor_total: '=AG8*AJ8',
    adjustment_equipment_total: '=AG8*AL8',
    adjustment_total_unit: '=AH8+AJ8+AL8',
    adjustment_total_total: '=AI8+AK8+AM8',
    remark: '',
  },
  {
    item: '조립식가설실험실',
    specification: '15개월',
    unit: 'M2',
    revision_cnt: 1,
    revision: '1차변경',
    contract_quantity: 20,
    contract_material_unit: 76302,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 20,
    plan_material_unit: 61876,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 20,
    execution_material_unit: 61876,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 20,
    adjustment_material_unit: 61876,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F9*G9',
    contract_labor_total: '=F9*I9',
    contract_equipment_total: '=F9*K9',
    contract_total_unit: '=G9+I9+K9',
    contract_total_total: '=H9+J9+L9',
    plan_material_total: '=O9*P9',
    plan_labor_total: '=O9*R9',
    plan_equipment_total: '=O9*T9',
    plan_total_unit: '=P9+R9+T9',
    plan_total_total: '=Q9+S9+U9',
    execution_material_total: '=X9*Y9',
    execution_labor_total: '=X9*AA9',
    execution_equipment_total: '=X9*AC9',
    execution_total_unit: '=Y9+AA9+AC9',
    execution_total_total: '=Z9+AB9+AD9',
    adjustment_material_total: '=AG9*AH9',
    adjustment_labor_total: '=AG9*AJ9',
    adjustment_equipment_total: '=AG9*AL9',
    adjustment_total_unit: '=AH9+AJ9+AL9',
    adjustment_total_total: '=AI9+AK9+AM9',
    remark: '',
  },
  {
    item: '공사용 가설전기 설치',
    specification: '분전반+강재전선관+배선',
    unit: '개소',
    revision_cnt: 0,
    revision: '최초',
    contract_quantity: 1,
    contract_material_unit: 437994,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 1,
    plan_material_unit: 355182,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 1,
    execution_material_unit: 355182,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 1,
    adjustment_material_unit: 355182,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F10*G10',
    contract_labor_total: '=F10*I10',
    contract_equipment_total: '=F10*K10',
    contract_total_unit: '=G10+I10+K10',
    contract_total_total: '=H10+J10+L10',
    plan_material_total: '=O10*P10',
    plan_labor_total: '=O10*R10',
    plan_equipment_total: '=O10*T10',
    plan_total_unit: '=P10+R10+T10',
    plan_total_total: '=Q10+S10+U10',
    execution_material_total: '=X10*Y10',
    execution_labor_total: '=X10*AA10',
    execution_equipment_total: '=X10*AC10',
    execution_total_unit: '=Y10+AA10+AC10',
    execution_total_total: '=Z10+AB10+AD10',
    adjustment_material_total: '=AG10*AH10',
    adjustment_labor_total: '=AG10*AJ10',
    adjustment_equipment_total: '=AG10*AL10',
    adjustment_total_unit: '=AH10+AJ10+AL10',
    adjustment_total_total: '=AI10+AK10+AM10',
    remark: '',
  },
  {
    item: '공사용 가설전기 설치',
    specification: '분전반+강재전선관+배선',
    unit: '개소',
    revision_cnt: 1,
    revision: '1차변경',
    contract_quantity: 1,
    contract_material_unit: 437994,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 1,
    plan_material_unit: 355182,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 1,
    execution_material_unit: 355182,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 1,
    adjustment_material_unit: 355182,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F11*G11',
    contract_labor_total: '=F11*I11',
    contract_equipment_total: '=F11*K11',
    contract_total_unit: '=G11+I11+K11',
    contract_total_total: '=H11+J11+L11',
    plan_material_total: '=O11*P11',
    plan_labor_total: '=O11*R11',
    plan_equipment_total: '=O11*T11',
    plan_total_unit: '=P11+R11+T11',
    plan_total_total: '=Q11+S11+U11',
    execution_material_total: '=X11*Y11',
    execution_labor_total: '=X11*AA11',
    execution_equipment_total: '=X11*AC11',
    execution_total_unit: '=Y11+AA11+AC11',
    execution_total_total: '=Z11+AB11+AD11',
    adjustment_material_total: '=AG11*AH11',
    adjustment_labor_total: '=AG11*AJ11',
    adjustment_equipment_total: '=AG11*AL11',
    adjustment_total_unit: '=AH11+AJ11+AL11',
    adjustment_total_total: '=AI11+AK11+AM11',
    remark: '',
  },
  {
    item: '방진망 설치 및 해제',
    specification: 'P.E, 1.5*150m',
    unit: 'M2',
    revision_cnt: 0,
    revision: '최초',
    contract_quantity: 10445,
    contract_material_unit: 4056,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 10445,
    plan_material_unit: 3289,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 10445,
    execution_material_unit: 3289,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 10445,
    adjustment_material_unit: 3289,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F12*G12',
    contract_labor_total: '=F12*I12',
    contract_equipment_total: '=F12*K12',
    contract_total_unit: '=G12+I12+K12',
    contract_total_total: '=H12+J12+L12',
    plan_material_total: '=O12*P12',
    plan_labor_total: '=O12*R12',
    plan_equipment_total: '=O12*T12',
    plan_total_unit: '=P12+R12+T12',
    plan_total_total: '=Q12+S12+U12',
    execution_material_total: '=X12*Y12',
    execution_labor_total: '=X12*AA12',
    execution_equipment_total: '=X12*AC12',
    execution_total_unit: '=Y12+AA12+AC12',
    execution_total_total: '=Z12+AB12+AD12',
    adjustment_material_total: '=AG12*AH12',
    adjustment_labor_total: '=AG12*AJ12',
    adjustment_equipment_total: '=AG12*AL12',
    adjustment_total_unit: '=AH12+AJ12+AL12',
    adjustment_total_total: '=AI12+AK12+AM12',
    remark: '',
  },
  {
    item: '방진망 설치 및 해제',
    specification: 'P.E, 1.5*150m',
    unit: 'M2',
    revision_cnt: 1,
    revision: '1차변경',
    contract_quantity: 10445,
    contract_material_unit: 4056,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 10445,
    plan_material_unit: 3289,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 10445,
    execution_material_unit: 3289,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 10445,
    adjustment_material_unit: 3289,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F13*G13',
    contract_labor_total: '=F13*I13',
    contract_equipment_total: '=F13*K13',
    contract_total_unit: '=G13+I13+K13',
    contract_total_total: '=H13+J13+L13',
    plan_material_total: '=O13*P13',
    plan_labor_total: '=O13*R13',
    plan_equipment_total: '=O13*T13',
    plan_total_unit: '=P13+R13+T13',
    plan_total_total: '=Q13+S13+U13',
    execution_material_total: '=X13*Y13',
    execution_labor_total: '=X13*AA13',
    execution_equipment_total: '=X13*AC13',
    execution_total_unit: '=Y13+AA13+AC13',
    execution_total_total: '=Z13+AB13+AD13',
    adjustment_material_total: '=AG13*AH13',
    adjustment_labor_total: '=AG13*AJ13',
    adjustment_equipment_total: '=AG13*AL13',
    adjustment_total_unit: '=AH13+AJ13+AL13',
    adjustment_total_total: '=AI13+AK13+AM13',
    remark: '',
  },
  {
    item: '쓰레기 슈트 설치',
    specification: 'D450mm, 12개월',
    unit: 'M',
    revision: '최초',
    contract_quantity: 35,
    contract_material_unit: 98708,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 35,
    plan_material_unit: 80045,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 35,
    execution_material_unit: 80045,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 35,
    adjustment_material_unit: 80045,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F14*G14',
    contract_labor_total: '=F14*I14',
    contract_equipment_total: '=F14*K14',
    contract_total_unit: '=G14+I14+K14',
    contract_total_total: '=H14+J14+L14',
    plan_material_total: '=O14*P14',
    plan_labor_total: '=O14*R14',
    plan_equipment_total: '=O14*T14',
    plan_total_unit: '=P14+R14+T14',
    plan_total_total: '=Q14+S14+U14',
    execution_material_total: '=X14*Y14',
    execution_labor_total: '=X14*AA14',
    execution_equipment_total: '=X14*AC14',
    execution_total_unit: '=Y14+AA14+AC14',
    execution_total_total: '=Z14+AB14+AD14',
    adjustment_material_total: '=AG14*AH14',
    adjustment_labor_total: '=AG14*AJ14',
    adjustment_equipment_total: '=AG14*AL14',
    adjustment_total_unit: '=AH14+AJ14+AL14',
    adjustment_total_total: '=AI14+AK14+AM14',
    remark: '',
  },
  {
    item: '쓰레기 슈트 설치',
    specification: 'D450mm, 12개월',
    unit: 'M',
    revision: '1차변경',
    contract_quantity: 35,
    contract_material_unit: 98708,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 35,
    plan_material_unit: 80045,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 35,
    execution_material_unit: 80045,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 35,
    adjustment_material_unit: 80045,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F15*G15',
    contract_labor_total: '=F15*I15',
    contract_equipment_total: '=F15*K15',
    contract_total_unit: '=G15+I15+K15',
    contract_total_total: '=H15+J15+L15',
    plan_material_total: '=O15*P15',
    plan_labor_total: '=O15*R15',
    plan_equipment_total: '=O15*T15',
    plan_total_unit: '=P15+R15+T15',
    plan_total_total: '=Q15+S15+U15',
    execution_material_total: '=X15*Y15',
    execution_labor_total: '=X15*AA15',
    execution_equipment_total: '=X15*AC15',
    execution_total_unit: '=Y15+AA15+AC15',
    execution_total_total: '=Z15+AB15+AD15',
    adjustment_material_total: '=AG15*AH15',
    adjustment_labor_total: '=AG15*AJ15',
    adjustment_equipment_total: '=AG15*AL15',
    adjustment_total_unit: '=AH15+AJ15+AL15',
    adjustment_total_total: '=AI15+AK15+AM15',
    remark: '',
  },
  {
    category: '소계',
    revision: '최초',
    contract_quantity: '=SUMIF(E4:E16, "최초", F4:F16)',
    contract_material_unit: '=SUMIF(E4:E16, "최초", G4:G16)',
    contract_material_total: '=SUMIF(E4:E16, "최초", H4:H16)',
    contract_labor_unit: '=SUMIF(E4:E16, "최초", I4:I16)',
    contract_labor_total: '=SUMIF(E4:E16, "최초", J4:J16)',
    contract_equipment_unit: '=SUMIF(E4:E16, "최초", K4:K16)',
    contract_equipment_total: '=SUMIF(E4:E16, "최초", L4:L16)',
    contract_total_unit: '=SUMIF(E4:E16, "최초", M4:M16)',
    contract_total_total: '=SUMIF(E4:E16, "최초", N4:N16)',
    plan_quantity: '=SUMIF(E4:E16, "최초", O4:O16)',
    plan_material_unit: '=SUMIF(E4:E16, "최초", P4:P16)',
    plan_material_total: '=SUMIF(E4:E16, "최초", Q4:Q16)',
    plan_labor_unit: '=SUMIF(E4:E16, "최초", R4:R16)',
    plan_labor_total: '=SUMIF(E4:E16, "최초", S4:S16)',
    plan_equipment_unit: '=SUMIF(E4:E16, "최초", T4:T16)',
    plan_equipment_total: '=SUMIF(E4:E16, "최초", U4:U16)',
    plan_total_unit: '=SUMIF(E4:E16, "최초", V4:V16)',
    plan_total_total: '=SUMIF(E4:E16, "최초", W4:W16)',
    execution_quantity: '=SUMIF(E4:E16, "최초", X4:X16)',
    execution_material_unit: '=SUMIF(E4:E16, "최초", Y4:Y16)',
    execution_material_total: '=SUMIF(E4:E16, "최초", Z4:Z16)',
    execution_labor_unit: '=SUMIF(E4:E16, "최초", AA4:AA16)',
    execution_labor_total: '=SUMIF(E4:E16, "최초", AB4:AB16)',
    execution_equipment_unit: '=SUMIF(E4:E16, "최초", AC4:AC16)',
    execution_equipment_total: '=SUMIF(E4:E16, "최초", AD4:AD16)',
    execution_total_unit: '=SUMIF(E4:E16, "최초", AE4:AE16)',
    execution_total_total: '=SUMIF(E4:E16, "최초", AF4:AF16)',
    adjustment_quantity: '=SUMIF(E4:E16, "최초", AG4:AG16)',
    adjustment_material_unit: '=SUMIF(E4:E16, "최초", AH4:AH16)',
    adjustment_material_total: '=SUMIF(E4:E16, "최초", AI4:AI16)',
    adjustment_labor_unit: '=SUMIF(E4:E16, "최초", AJ4:AJ16)',
    adjustment_labor_total: '=SUMIF(E4:E16, "최초", AK4:AK16)',
    adjustment_equipment_unit: '=SUMIF(E4:E16, "최초", AL4:AL16)',
    adjustment_equipment_total: '=SUMIF(E4:E16, "최초", AM4:AM16)',
    adjustment_total_unit: '=SUMIF(E4:E16, "최초", AN4:AN16)',
    adjustment_total_total: '=SUMIF(E4:E16, "최초", AO4:AO16)',
  },
  {
    category: '소계',
    revision: '1차변경',
    contract_quantity: '=SUMIF(E4:E16, "1차변경", F4:F16)',
    contract_material_unit: '=SUMIF(E4:E16, "1차변경", G4:G16)',
    contract_material_total: '=SUMIF(E4:E16, "1차변경", H4:H16)',
    contract_labor_unit: '=SUMIF(E4:E16, "1차변경", I4:I16)',
    contract_labor_total: '=SUMIF(E4:E16, "1차변경", J4:J16)',
    contract_equipment_unit: '=SUMIF(E4:E16, "1차변경", K4:K16)',
    contract_equipment_total: '=SUMIF(E4:E16, "1차변경", L4:L16)',
    contract_total_unit: '=SUMIF(E4:E16, "1차변경", M4:M16)',
    contract_total_total: '=SUMIF(E4:E16, "1차변경", N4:N16)',
    plan_quantity: '=SUMIF(E4:E16, "1차변경", O4:O16)',
    plan_material_unit: '=SUMIF(E4:E16, "1차변경", P4:P16)',
    plan_material_total: '=SUMIF(E4:E16, "1차변경", Q4:Q16)',
    plan_labor_unit: '=SUMIF(E4:E16, "1차변경", R4:R16)',
    plan_labor_total: '=SUMIF(E4:E16, "1차변경", S4:S16)',
    plan_equipment_unit: '=SUMIF(E4:E16, "1차변경", T4:T16)',
    plan_equipment_total: '=SUMIF(E4:E16, "1차변경", U4:U16)',
    plan_total_unit: '=SUMIF(E4:E16, "1차변경", V4:V16)',
    plan_total_total: '=SUMIF(E4:E16, "1차변경", W4:W16)',
    execution_quantity: '=SUMIF(E4:E16, "1차변경", X4:X16)',
    execution_material_unit: '=SUMIF(E4:E16, "1차변경", Y4:Y16)',
    execution_material_total: '=SUMIF(E4:E16, "1차변경", Z4:Z16)',
    execution_labor_unit: '=SUMIF(E4:E16, "1차변경", AA4:AA16)',
    execution_labor_total: '=SUMIF(E4:E16, "1차변경", AB4:AB16)',
    execution_equipment_unit: '=SUMIF(E4:E16, "1차변경", AC4:AC16)',
    execution_equipment_total: '=SUMIF(E4:E16, "1차변경", AD4:AD16)',
    execution_total_unit: '=SUMIF(E4:E16, "1차변경", AE4:AE16)',
    execution_total_total: '=SUMIF(E4:E16, "1차변경", AF4:AF16)',
    adjustment_quantity: '=SUMIF(E4:E16, "1차변경", AG4:AG16)',
    adjustment_material_unit: '=SUMIF(E4:E16, "1차변경", AH4:AH16)',
    adjustment_material_total: '=SUMIF(E4:E16, "1차변경", AI4:AI16)',
    adjustment_labor_unit: '=SUMIF(E4:E16, "1차변경", AJ4:AJ16)',
    adjustment_labor_total: '=SUMIF(E4:E16, "1차변경", AK4:AK16)',
    adjustment_equipment_unit: '=SUMIF(E4:E16, "1차변경", AL4:AL16)',
    adjustment_equipment_total: '=SUMIF(E4:E16, "1차변경", AM4:AM16)',
    adjustment_total_unit: '=SUMIF(E4:E16, "1차변경", AN4:AN16)',
    adjustment_total_total: '=SUMIF(E4:E16, "1차변경", AO4:AO16)',
  },
  {
    category: '건축 > 가설공사',
    item: '조립말비계 (강관)',
    specification: '3개월 이하 1단,2m',
    unit: '대',
    revision: '1차변경',
    contract_quantity: 75,
    contract_material_unit: 18431,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 75,
    plan_material_unit: 14946,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 75,
    execution_material_unit: 14946,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 75,
    adjustment_material_unit: 14946,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F18*G18',
    contract_labor_total: '=F18*I18',
    contract_equipment_total: '=F18*K18',
    contract_total_unit: '=G18+I18+K18',
    contract_total_total: '=H18+J18+L18',
    plan_material_total: '=O18*P18',
    plan_labor_total: '=O18*R18',
    plan_equipment_total: '=O18*T18',
    plan_total_unit: '=P18+R18+T18',
    plan_total_total: '=Q18+S18+U18',
    execution_material_total: '=X18*Y18',
    execution_labor_total: '=X18*AA18',
    execution_equipment_total: '=X18*AC18',
    execution_total_unit: '=Y18+AA18+AC18',
    execution_total_total: '=Z18+AB18+AD18',
    adjustment_material_total: '=AG18*AH18',
    adjustment_labor_total: '=AG18*AJ18',
    adjustment_equipment_total: '=AG18*AL18',
    adjustment_total_unit: '=AH18+AJ18+AL18',
    adjustment_total_total: '=AI18+AK18+AM18',
    remark: '',
  },
  {
    item: '수평 규준틀',
    specification: '평',
    unit: '개소',
    revision: '1차변경',
    contract_quantity: 52,
    contract_material_unit: 6487,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 52,
    plan_material_unit: 5261,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 52,
    execution_material_unit: 5261,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 52,
    adjustment_material_unit: 5261,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F19*G19',
    contract_labor_total: '=F19*I19',
    contract_equipment_total: '=F19*K19',
    contract_total_unit: '=G19+I19+K19',
    contract_total_total: '=H19+J19+L19',
    plan_material_total: '=O19*P19',
    plan_labor_total: '=O19*R19',
    plan_equipment_total: '=O19*T19',
    plan_total_unit: '=P19+R19+T19',
    plan_total_total: '=Q19+S19+U19',
    execution_material_total: '=X19*Y19',
    execution_labor_total: '=X19*AA19',
    execution_equipment_total: '=X19*AC19',
    execution_total_unit: '=Y19+AA19+AC19',
    execution_total_total: '=Z19+AB19+AD19',
    adjustment_material_total: '=AG19*AH19',
    adjustment_labor_total: '=AG19*AJ19',
    adjustment_equipment_total: '=AG19*AL19',
    adjustment_total_unit: '=AH19+AJ19+AL19',
    adjustment_total_total: '=AI19+AK19+AM19',
    remark: '',
  },
  {
    item: '시스템동바리 설치 및 해체',
    specification: 'H=10m이하, 3개월',
    unit: 'M3',
    revision: '1차변경',
    contract_quantity: 10474,
    contract_material_unit: 2208,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 10474,
    plan_material_unit: 1791,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 10474,
    execution_material_unit: 1791,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 10474,
    adjustment_material_unit: 1791,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F20*G20',
    contract_labor_total: '=F20*I20',
    contract_equipment_total: '=F20*K20',
    contract_total_unit: '=G20+I20+K20',
    contract_total_total: '=H20+J20+L20',
    plan_material_total: '=O20*P20',
    plan_labor_total: '=O20*R20',
    plan_equipment_total: '=O20*T20',
    plan_total_unit: '=P20+R20+T20',
    plan_total_total: '=Q20+S20+U20',
    execution_material_total: '=X20*Y20',
    execution_labor_total: '=X20*AA20',
    execution_equipment_total: '=X20*AC20',
    execution_total_unit: '=Y20+AA20+AC20',
    execution_total_total: '=Z20+AB20+AD20',
    adjustment_material_total: '=AG20*AH20',
    adjustment_labor_total: '=AG20*AJ20',
    adjustment_equipment_total: '=AG20*AL20',
    adjustment_total_unit: '=AH20+AJ20+AL20',
    adjustment_total_total: '=AI20+AK20+AM20',
    remark: '',
  },
  {
    item: '콘크리트 양생',
    specification: '살수',
    unit: '㎡',
    revision: '1차변경',
    contract_quantity: 22172,
    contract_material_unit: 0,
    contract_labor_unit: 0,
    contract_equipment_unit: 0,
    plan_quantity: 22172,
    plan_material_unit: 0,
    plan_labor_unit: 0,
    plan_equipment_unit: 0,
    execution_quantity: 22172,
    execution_material_unit: 0,
    execution_labor_unit: 0,
    execution_equipment_unit: 0,
    adjustment_quantity: 22172,
    adjustment_material_unit: 0,
    adjustment_labor_unit: 0,
    adjustment_equipment_unit: 0,
    contract_material_total: '=F21*G21',
    contract_labor_total: '=F21*I21',
    contract_equipment_total: '=F21*K21',
    contract_total_unit: '=G21+I21+K21',
    contract_total_total: '=H21+J21+L21',
    plan_material_total: '=O21*P21',
    plan_labor_total: '=O21*R21',
    plan_equipment_total: '=O21*T21',
    plan_total_unit: '=P21+R21+T21',
    plan_total_total: '=Q21+S21+U21',
    execution_material_total: '=X21*Y21',
    execution_labor_total: '=X21*AA21',
    execution_equipment_total: '=X21*AC21',
    execution_total_unit: '=Y21+AA21+AC21',
    execution_total_total: '=Z21+AB21+AD21',
    adjustment_material_total: '=AG21*AH21',
    adjustment_labor_total: '=AG21*AJ21',
    adjustment_equipment_total: '=AG21*AL21',
    adjustment_total_unit: '=AH21+AJ21+AL21',
    adjustment_total_total: '=AI21+AK21+AM21',
    remark: '',
  },
  {
    category: '소계',
    revision: '1차변경',
    contract_quantity: '=SUMIF(E18:E21, "1차변경", F18:F21)',
    contract_material_unit: '=SUMIF(E18:E21, "1차변경", G18:G21)',
    contract_material_total: '=SUMIF(E18:E21, "1차변경", H18:H21)',
    contract_labor_unit: '=SUMIF(E18:E21, "1차변경", I18:I21)',
    contract_labor_total: '=SUMIF(E18:E21, "1차변경", J18:J21)',
    contract_equipment_unit: '=SUMIF(E18:E21, "1차변경", K18:K21)',
    contract_equipment_total: '=SUMIF(E18:E21, "1차변경", L18:L21)',
    contract_total_unit: '=SUMIF(E18:E21, "1차변경", M18:M21)',
    contract_total_total: '=SUMIF(E18:E21, "1차변경", N18:N21)',
    plan_quantity: '=SUMIF(E18:E21, "1차변경", O18:O21)',
    plan_material_unit: '=SUMIF(E18:E21, "1차변경", P18:P21)',
    plan_material_total: '=SUMIF(E18:E21, "1차변경", Q18:Q21)',
    plan_labor_unit: '=SUMIF(E18:E21, "1차변경", R18:R21)',
    plan_labor_total: '=SUMIF(E18:E21, "1차변경", S18:S21)',
    plan_equipment_unit: '=SUMIF(E18:E21, "1차변경", T18:T21)',
    plan_equipment_total: '=SUMIF(E18:E21, "1차변경", U18:U21)',
    plan_total_unit: '=SUMIF(E18:E21, "1차변경", V18:V21)',
    plan_total_total: '=SUMIF(E18:E21, "1차변경", W18:W21)',
    execution_quantity: '=SUMIF(E18:E21, "1차변경", X18:X21)',
    execution_material_unit: '=SUMIF(E18:E21, "1차변경", Y18:Y21)',
    execution_material_total: '=SUMIF(E18:E21, "1차변경", Z18:Z21)',
    execution_labor_unit: '=SUMIF(E18:E21, "1차변경", AA18:AA21)',
    execution_labor_total: '=SUMIF(E18:E21, "1차변경", AB18:AB21)',
    execution_equipment_unit: '=SUMIF(E18:E21, "1차변경", AC18:AC21)',
    execution_equipment_total: '=SUMIF(E18:E21, "1차변경", AD18:AD21)',
    execution_total_unit: '=SUMIF(E18:E21, "1차변경", AE18:AE21)',
    execution_total_total: '=SUMIF(E18:E21, "1차변경", AF18:AF21)',
    adjustment_quantity: '=SUMIF(E18:E21, "1차변경", AG18:AG21)',
    adjustment_material_unit: '=SUMIF(E18:E21, "1차변경", AH18:AH21)',
    adjustment_material_total: '=SUMIF(E18:E21, "1차변경", AI18:AI21)',
    adjustment_labor_unit: '=SUMIF(E18:E21, "1차변경", AJ18:AJ21)',
    adjustment_labor_total: '=SUMIF(E18:E21, "1차변경", AK18:AK21)',
    adjustment_equipment_unit: '=SUMIF(E18:E21, "1차변경", AL18:AL21)',
    adjustment_equipment_total: '=SUMIF(E18:E21, "1차변경", AM18:AM21)',
    adjustment_total_unit: '=SUMIF(E18:E21, "1차변경", AN18:AN21)',
    adjustment_total_total: '=SUMIF(E18:E21, "1차변경", AO18:AO21)',
  },
  {
    category: '간접비',
    item: '작업설 부산물',
    specification: '단가의',
    unit: '100%',
    revision: '최초',
    contract_material_total: '=F23*G23',
    plan_material_total: '=O23*P23',
    execution_material_total: '=X23*Y23',
    adjustment_material_total: '=AG23*AH23',
    remark: '',
  },
  {
    item: '작업설 부산물',
    specification: '단가의',
    unit: '100%',
    revision: '1차변경',
    contract_material_total: '=F24*G24',
    plan_material_total: '=O24*P24',
    execution_material_total: '=X24*Y24',
    adjustment_material_total: '=AG24*AH24',
    remark: '',
  },
  {
    item: '간접노무비',
    specification: '(직.노) 의',
    unit: '10.20%',
    revision: '최초',
    contract_material_total: '=F25*G25',
    plan_material_total: '=O25*P25',
    execution_material_total: '=X25*Y25',
    adjustment_material_total: '=AG25*AH25',
    remark: '',
  },
  {
    item: '간접노무비',
    specification: '(직.노) 의',
    unit: '10.20%',
    revision: '1차변경',
    contract_material_total: '=F26*G26',
    plan_material_total: '=O26*P26',
    execution_material_total: '=X26*Y26',
    adjustment_material_total: '=AG26*AH26',
    remark: '',
  },
  {
    item: '운반비',
    specification: '단가의',
    unit: '100.00%',
    revision: '최초',
    contract_material_total: '=F27*G27',
    plan_material_total: '=O27*P27',
    execution_material_total: '=X27*Y27',
    adjustment_material_total: '=AG27*AH27',
    remark: '',
  },
  {
    item: '운반비',
    specification: '단가의',
    unit: '100.00%',
    revision: '1차변경',
    contract_material_total: '=F28*G28',
    plan_material_total: '=O28*P28',
    execution_material_total: '=X28*Y28',
    adjustment_material_total: '=AG28*AH28',
    remark: '',
  },
  {
    item: '산재보험료',
    specification: '(직.노+간.노)의',
    unit: '3.80%',
    revision: '최초',
    contract_material_total: '=F29*G29',
    plan_material_total: '=O29*P29',
    execution_material_total: '=X29*Y29',
    adjustment_material_total: '=AG29*AH29',
    remark: '',
  },
  {
    item: '산재보험료',
    specification: '(직.노+간.노)의',
    unit: '3.80%',
    revision: '1차변경',
    contract_material_total: '=F30*G30',
    plan_material_total: '=O30*P30',
    execution_material_total: '=X30*Y30',
    adjustment_material_total: '=AG30*AH30',
    remark: '',
  },
  {
    item: '고용보험료',
    specification: '(직.노+간.노)의',
    unit: '0.67%',
    revision: '최초',
    contract_material_total: '=F31*G31',
    plan_material_total: '=O31*P31',
    execution_material_total: '=X31*Y31',
    adjustment_material_total: '=AG31*AH31',
    remark: '',
  },
  {
    item: '고용보험료',
    specification: '(직.노+간.노)의',
    unit: '0.67%',
    revision: '1차변경',
    contract_material_total: '=F32*G32',
    plan_material_total: '=O32*P32',
    execution_material_total: '=X32*Y32',
    adjustment_material_total: '=AG32*AH32',
    remark: '',
  },
  {
    item: '건강보험료',
    specification: '(직.노) 의',
    unit: '1.25%',
    revision: '최초',
    contract_material_total: '=F33*G33',
    plan_material_total: '=O33*P33',
    execution_material_total: '=X33*Y33',
    adjustment_material_total: '=AG33*AH33',
    remark: '',
  },
  {
    item: '건강보험료',
    specification: '(직.노) 의',
    unit: '1.25%',
    revision: '1차변경',
    contract_material_total: '=F34*G34',
    plan_material_total: '=O34*P34',
    execution_material_total: '=X34*Y34',
    adjustment_material_total: '=AG34*AH34',
    remark: '',
  },
  {
    item: '연금보험료',
    specification: '(직.노) 의',
    unit: '2.41%',
    revision: '최초',
    contract_material_total: '=F35*G35',
    plan_material_total: '=O35*P35',
    execution_material_total: '=X35*Y35',
    adjustment_material_total: '=AG35*AH35',
    remark: '',
  },
  {
    item: '연금보험료',
    specification: '(직.노) 의',
    unit: '2.41%',
    revision: '1차변경',
    contract_material_total: '=F36*G36',
    plan_material_total: '=O36*P36',
    execution_material_total: '=X36*Y36',
    adjustment_material_total: '=AG36*AH36',
    remark: '',
  },
  {
    item: '국민노인장기요양보험료',
    specification: '(건강보험료)의',
    unit: '4.78%',
    revision: '최초',
    contract_material_total: '=F37*G37',
    plan_material_total: '=O37*P37',
    execution_material_total: '=X37*Y37',
    adjustment_material_total: '=AG37*AH37',
    remark: '',
  },
  {
    item: '국민노인장기요양보험료',
    specification: '(건강보험료)의',
    unit: '4.78%',
    revision: '1차변경',
    contract_material_total: '=F38*G38',
    plan_material_total: '=O38*P38',
    execution_material_total: '=X38*Y38',
    adjustment_material_total: '=AG38*AH38',
    remark: '',
  },
  {
    item: '퇴직공제부금',
    specification: '(직.노) 의',
    unit: '2.04%',
    revision: '최초',
    contract_material_total: '=F39*G39',
    plan_material_total: '=O39*P39',
    execution_material_total: '=X39*Y39',
    adjustment_material_total: '=AG39*AH39',
    remark: '',
  },
  {
    item: '퇴직공제부금',
    specification: '(직.노) 의',
    unit: '2.04%',
    revision: '1차변경',
    contract_material_total: '=F40*G40',
    plan_material_total: '=O40*P40',
    execution_material_total: '=X40*Y40',
    adjustment_material_total: '=AG40*AH40',
    remark: '',
  },
  {
    item: '재료시험비',
    specification: '단가의',
    unit: '100.00%',
    revision: '최초',
    contract_material_total: '=F41*G41',
    plan_material_total: '=O41*P41',
    execution_material_total: '=X41*Y41',
    adjustment_material_total: '=AG41*AH41',
    remark: '',
  },
  {
    item: '재료시험비',
    specification: '단가의',
    unit: '100.00%',
    revision: '1차변경',
    contract_material_total: '=F42*G42',
    plan_material_total: '=O42*P42',
    execution_material_total: '=X42*Y42',
    adjustment_material_total: '=AG42*AH42',
    remark: '',
  },
  {
    item: '산업안전보건관리비',
    specification: '(직.재-부산물+직.노)  의',
    unit: '1.81%',
    revision: '최초',
    contract_material_total: '=F43*G43',
    plan_material_total: '=O43*P43',
    execution_material_total: '=X43*Y43',
    adjustment_material_total: '=AG43*AH43',
    remark: '',
  },
  {
    item: '산업안전보건관리비',
    specification: '(직.재-부산물+직.노)  의',
    unit: '1.81%',
    revision: '1차변경',
    contract_material_total: '=F44*G44',
    plan_material_total: '=O44*P44',
    execution_material_total: '=X44*Y44',
    adjustment_material_total: '=AG44*AH44',
    remark: '',
  },
  {
    item: '기타경비',
    specification: '(직.재-부산물+직.노+간.노) 의',
    unit: '5.60%',
    revision: '최초',
    contract_material_total: '=F45*G45',
    plan_material_total: '=O45*P45',
    execution_material_total: '=X45*Y45',
    adjustment_material_total: '=AG45*AH45',
    remark: '',
  },
  {
    item: '기타경비',
    specification: '(직.재-부산물+직.노+간.노) 의',
    unit: '5.60%',
    revision: '1차변경',
    contract_material_total: '=F46*G46',
    plan_material_total: '=O46*P46',
    execution_material_total: '=X46*Y46',
    adjustment_material_total: '=AG46*AH46',
    remark: '',
  },
  {
    item: '공사이행보증수수료',
    specification: '(직.재-부산물+직.노+산출경비) 의',
    unit: '0.03%',
    revision: '최초',
    contract_material_total: '=F47*G47',
    plan_material_total: '=O47*P47',
    execution_material_total: '=X47*Y47',
    adjustment_material_total: '=AG47*AH47',
    remark: '',
  },
  {
    item: '공사이행보증수수료',
    specification: '(직.재-부산물+직.노+산출경비) 의',
    unit: '0.03%',
    revision: '1차변경',
    contract_material_total: '=F48*G48',
    plan_material_total: '=O48*P48',
    execution_material_total: '=X48*Y48',
    adjustment_material_total: '=AG48*AH48',
    remark: '',
  },
  {
    item: '건설하도급대금지급보증서(수수료)',
    specification: '(직.재-부산물+직.노+산출경비) 의',
    unit: '0.02%',
    revision: '최초',
    contract_material_total: '=F49*G49',
    plan_material_total: '=O49*P49',
    execution_material_total: '=X49*Y49',
    adjustment_material_total: '=AG49*AH49',
    remark: '',
  },
  {
    item: '건설하도급대금지급보증서(수수료)',
    specification: '(직.재-부산물+직.노+산출경비) 의',
    unit: '0.02%',
    revision: '1차변경',
    contract_material_total: '=F50*G50',
    plan_material_total: '=O50*P50',
    execution_material_total: '=X50*Y50',
    adjustment_material_total: '=AG50*AH50',
    remark: '',
  },
  {
    item: '환경보전비',
    specification: '(직.재-부산물+직.노+산출경비) 의',
    unit: '0.51%',
    revision: '최초',
    contract_material_total: '=F51*G51',
    plan_material_total: '=O51*P51',
    execution_material_total: '=X51*Y51',
    adjustment_material_total: '=AG51*AH51',
    remark: '',
  },
  {
    item: '환경보전비',
    specification: '(직.재-부산물+직.노+산출경비) 의',
    unit: '0.51%',
    revision: '1차변경',
    contract_material_total: '=F52*G52',
    plan_material_total: '=O52*P52',
    execution_material_total: '=X52*Y52',
    adjustment_material_total: '=AG52*AH52',
    remark: '',
  },
  {
    item: '일반관리비',
    specification: '(재.노.경+상부금액합) 의',
    unit: '4.70%',
    revision: '최초',
    contract_material_total: '=F53*G53',
    plan_material_total: '=O53*P53',
    execution_material_total: '=X53*Y53',
    adjustment_material_total: '=AG53*AH53',
    remark: '',
  },
  {
    item: '일반관리비',
    specification: '(재.노.경+상부금액합) 의',
    unit: '4.70%',
    revision: '1차변경',
    contract_material_total: '=F54*G54',
    plan_material_total: '=O54*P54',
    execution_material_total: '=X54*Y54',
    adjustment_material_total: '=AG54*AH54',
    remark: '',
  },
  {
    item: '이윤',
    specification: '(직.노+간.노+산출경비+일반관리비) 의',
    unit: '15.00%',
    revision: '최초',
    contract_material_total: '=F55*G55',
    plan_material_total: '=O55*P55',
    execution_material_total: '=X55*Y55',
    adjustment_material_total: '=AG55*AH55',
    remark: '',
  },
  {
    item: '이윤',
    specification: '(직.노+간.노+산출경비+일반관리비) 의',
    unit: '15.00%',
    revision: '1차변경',
    contract_material_total: '=F56*G56',
    plan_material_total: '=O56*P56',
    execution_material_total: '=X56*Y56',
    adjustment_material_total: '=AG56*AH56',
    remark: '',
  },
  {
    item: '폐기물처리비',
    specification: '단가의',
    unit: '100.00%',
    revision: '최초',
    contract_material_total: '=F57*G57',
    plan_material_total: '=O57*P57',
    execution_material_total: '=X57*Y57',
    adjustment_material_total: '=AG57*AH57',
    remark: '',
  },
  {
    item: '폐기물처리비',
    specification: '단가의',
    unit: '100.00%',
    revision: '1차변경',
    contract_material_total: '=F58*G58',
    plan_material_total: '=O58*P58',
    execution_material_total: '=X58*Y58',
    adjustment_material_total: '=AG58*AH58',
    remark: '',
  },
  {
    category: '소계',
    revision: '최초',
    contract_quantity: '=SUMIF(E23:E58, "최초", F23:F58)',
    contract_material_unit: '=SUMIF(E23:E58, "최초", G23:G58)',
    contract_material_total: '=SUMIF(E23:E58, "최초", H23:H58)',
    contract_labor_unit: '=SUMIF(E23:E58, "최초", I23:I58)',
    contract_labor_total: '=SUMIF(E23:E58, "최초", J23:J58)',
    contract_equipment_unit: '=SUMIF(E23:E58, "최초", K23:K58)',
    contract_equipment_total: '=SUMIF(E23:E58, "최초", L23:L58)',
    contract_total_unit: '=SUMIF(E23:E58, "최초", M23:M58)',
    contract_total_total: '=SUMIF(E23:E58, "최초", N23:N58)',
    plan_quantity: '=SUMIF(E23:E58, "최초", O23:O58)',
    plan_material_unit: '=SUMIF(E23:E58, "최초", P23:P58)',
    plan_material_total: '=SUMIF(E23:E58, "최초", Q23:Q58)',
    plan_labor_unit: '=SUMIF(E23:E58, "최초", R23:R58)',
    plan_labor_total: '=SUMIF(E23:E58, "최초", S23:S58)',
    plan_equipment_unit: '=SUMIF(E23:E58, "최초", T23:T58)',
    plan_equipment_total: '=SUMIF(E23:E58, "최초", U23:U58)',
    plan_total_unit: '=SUMIF(E23:E58, "최초", V23:V58)',
    plan_total_total: '=SUMIF(E23:E58, "최초", W23:W58)',
    execution_quantity: '=SUMIF(E23:E58, "최초", X23:X58)',
    execution_material_unit: '=SUMIF(E23:E58, "최초", Y23:Y58)',
    execution_material_total: '=SUMIF(E23:E58, "최초", Z23:Z58)',
    execution_labor_unit: '=SUMIF(E23:E58, "최초", AA23:AA58)',
    execution_labor_total: '=SUMIF(E23:E58, "최초", AB23:AB58)',
    execution_equipment_unit: '=SUMIF(E23:E58, "최초", AC23:AC58)',
    execution_equipment_total: '=SUMIF(E23:E58, "최초", AD23:AD58)',
    execution_total_unit: '=SUMIF(E23:E58, "최초", AE23:AE58)',
    execution_total_total: '=SUMIF(E23:E58, "최초", AF23:AF58)',
    adjustment_quantity: '=SUMIF(E23:E58, "최초", AG23:AG58)',
    adjustment_material_unit: '=SUMIF(E23:E58, "최초", AH23:AH58)',
    adjustment_material_total: '=SUMIF(E23:E58, "최초", AI23:AI58)',
    adjustment_labor_unit: '=SUMIF(E23:E58, "최초", AJ23:AJ58)',
    adjustment_labor_total: '=SUMIF(E23:E58, "최초", AK23:AK58)',
    adjustment_equipment_unit: '=SUMIF(E23:E58, "최초", AL23:AL58)',
    adjustment_equipment_total: '=SUMIF(E23:E58, "최초", AM23:AM58)',
    adjustment_total_unit: '=SUMIF(E23:E58, "최초", AN23:AN58)',
    adjustment_total_total: '=SUMIF(E23:E58, "최초", AO23:AO58)',
  },
  {
    category: '소계',
    revision: '1차변경',
    contract_quantity: '=SUMIF(E23:E58, "1차변경", F23:F58)',
    contract_material_unit: '=SUMIF(E23:E58, "1차변경", G23:G58)',
    contract_material_total: '=SUMIF(E23:E58, "1차변경", H23:H58)',
    contract_labor_unit: '=SUMIF(E23:E58, "1차변경", I23:I58)',
    contract_labor_total: '=SUMIF(E23:E58, "1차변경", J23:J58)',
    contract_equipment_unit: '=SUMIF(E23:E58, "1차변경", K23:K58)',
    contract_equipment_total: '=SUMIF(E23:E58, "1차변경", L23:L58)',
    contract_total_unit: '=SUMIF(E23:E58, "1차변경", M23:M58)',
    contract_total_total: '=SUMIF(E23:E58, "1차변경", N23:N58)',
    plan_quantity: '=SUMIF(E23:E58, "1차변경", O23:O58)',
    plan_material_unit: '=SUMIF(E23:E58, "1차변경", P23:P58)',
    plan_material_total: '=SUMIF(E23:E58, "1차변경", Q23:Q58)',
    plan_labor_unit: '=SUMIF(E23:E58, "1차변경", R23:R58)',
    plan_labor_total: '=SUMIF(E23:E58, "1차변경", S23:S58)',
    plan_equipment_unit: '=SUMIF(E23:E58, "1차변경", T23:T58)',
    plan_equipment_total: '=SUMIF(E23:E58, "1차변경", U23:U58)',
    plan_total_unit: '=SUMIF(E23:E58, "1차변경", V23:V58)',
    plan_total_total: '=SUMIF(E23:E58, "1차변경", W23:W58)',
    execution_quantity: '=SUMIF(E23:E58, "1차변경", X23:X58)',
    execution_material_unit: '=SUMIF(E23:E58, "1차변경", Y23:Y58)',
    execution_material_total: '=SUMIF(E23:E58, "1차변경", Z23:Z58)',
    execution_labor_unit: '=SUMIF(E23:E58, "1차변경", AA23:AA58)',
    execution_labor_total: '=SUMIF(E23:E58, "1차변경", AB23:AB58)',
    execution_equipment_unit: '=SUMIF(E23:E58, "1차변경", AC23:AC58)',
    execution_equipment_total: '=SUMIF(E23:E58, "1차변경", AD23:AD58)',
    execution_total_unit: '=SUMIF(E23:E58, "1차변경", AE23:AE58)',
    execution_total_total: '=SUMIF(E23:E58, "1차변경", AF23:AF58)',
    adjustment_quantity: '=SUMIF(E23:E58, "1차변경", AG23:AG58)',
    adjustment_material_unit: '=SUMIF(E23:E58, "1차변경", AH23:AH58)',
    adjustment_material_total: '=SUMIF(E23:E58, "1차변경", AI23:AI58)',
    adjustment_labor_unit: '=SUMIF(E23:E58, "1차변경", AJ23:AJ58)',
    adjustment_labor_total: '=SUMIF(E23:E58, "1차변경", AK23:AK58)',
    adjustment_equipment_unit: '=SUMIF(E23:E58, "1차변경", AL23:AL58)',
    adjustment_equipment_total: '=SUMIF(E23:E58, "1차변경", AM23:AM58)',
    adjustment_total_unit: '=SUMIF(E23:E58, "1차변경", AN23:AN58)',
    adjustment_total_total: '=SUMIF(E23:E58, "1차변경", AO23:AO58)',
  },
  {
    category: '합계',
    revision: '최초',
    contract_quantity: '=SUMIFS(F4:F58, A4:A58, "소계", E4:E58, "최초")',
    contract_material_unit: '=SUMIFS(G4:G58, A4:A58, "소계", E4:E58, "최초")',
    contract_material_total: '=SUMIFS(H4:H58, A4:A58, "소계", E4:E58, "최초")',
    contract_labor_unit: '=SUMIFS(I4:I58, A4:A58, "소계", E4:E58, "최초")',
    contract_labor_total: '=SUMIFS(J4:J58, A4:A58, "소계", E4:E58, "최초")',
    contract_equipment_unit: '=SUMIFS(K4:K58, A4:A58, "소계", E4:E58, "최초")',
    contract_equipment_total: '=SUMIFS(L4:L58, A4:A58, "소계", E4:E58, "최초")',
    contract_total_unit: '=SUMIFS(M4:M58, A4:A58, "소계", E4:E58, "최초")',
    contract_total_total: '=SUMIFS(N4:N58, A4:A58, "소계", E4:E58, "최초")',
    plan_quantity: '=SUMIFS(O4:O58, A4:A58, "소계", E4:E58, "최초")',
    plan_material_unit: '=SUMIFS(P4:P58, A4:A58, "소계", E4:E58, "최초")',
    plan_material_total: '=SUMIFS(Q4:Q58, A4:A58, "소계", E4:E58, "최초")',
    plan_labor_unit: '=SUMIFS(R4:R58, A4:A58, "소계", E4:E58, "최초")',
    plan_labor_total: '=SUMIFS(S4:S58, A4:A58, "소계", E4:E58, "최초")',
    plan_equipment_unit: '=SUMIFS(T4:T58, A4:A58, "소계", E4:E58, "최초")',
    plan_equipment_total: '=SUMIFS(U4:U58, A4:A58, "소계", E4:E58, "최초")',
    plan_total_unit: '=SUMIFS(V4:V58, A4:A58, "소계", E4:E58, "최초")',
    plan_total_total: '=SUMIFS(W4:W58, A4:A58, "소계", E4:E58, "최초")',
    execution_quantity: '=SUMIFS(X4:X58, A4:A58, "소계", E4:E58, "최초")',
    execution_material_unit: '=SUMIFS(Y4:Y58, A4:A58, "소계", E4:E58, "최초")',
    execution_material_total: '=SUMIFS(Z4:Z58, A4:A58, "소계", E4:E58, "최초")',
    execution_labor_unit: '=SUMIFS(AA4:AA58, A4:A58, "소계", E4:E58, "최초")',
    execution_labor_total: '=SUMIFS(AB4:AB58, A4:A58, "소계", E4:E58, "최초")',
    execution_equipment_unit: '=SUMIFS(AC4:AC58, A4:A58, "소계", E4:E58, "최초")',
    execution_equipment_total: '=SUMIFS(AD4:AD58, A4:A58, "소계", E4:E58, "최초")',
    execution_total_unit: '=SUMIFS(AE4:AE58, A4:A58, "소계", E4:E58, "최초")',
    execution_total_total: '=SUMIFS(AF4:AF58, A4:A58, "소계", E4:E58, "최초")',
    adjustment_quantity: '=SUMIFS(AG4:AG58, A4:A58, "소계", E4:E58, "최초")',
    adjustment_material_unit: '=SUMIFS(AH4:AH58, A4:A58, "소계", E4:E58, "최초")',
    adjustment_material_total: '=SUMIFS(AI4:AI58, A4:A58, "소계", E4:E58, "최초")',
    adjustment_labor_unit: '=SUMIFS(AJ4:AJ58, A4:A58, "소계", E4:E58, "최초")',
    adjustment_labor_total: '=SUMIFS(AK4:AK58, A4:A58, "소계", E4:E58, "최초")',
    adjustment_equipment_unit: '=SUMIFS(AL4:AL58, A4:A58, "소계", E4:E58, "최초")',
    adjustment_equipment_total: '=SUMIFS(AM4:AM58, A4:A58, "소계", E4:E58, "최초")',
    adjustment_total_unit: '=SUMIFS(AN4:AN58, A4:A58, "소계", E4:E58, "최초")',
    adjustment_total_total: '=SUMIFS(AO4:AO58, A4:A58, "소계", E4:E58, "최초")',
  },
  {
    category: '합계',
    revision: '1차변경',
    contract_quantity: '=SUMIFS(F4:F58, A4:A58, "소계", E4:E58, "1차변경")',
    contract_material_unit: '=SUMIFS(G4:G58, A4:A58, "소계", E4:E58, "1차변경")',
    contract_material_total: '=SUMIFS(H4:H58, A4:A58, "소계", E4:E58, "1차변경")',
    contract_labor_unit: '=SUMIFS(I4:I58, A4:A58, "소계", E4:E58, "1차변경")',
    contract_labor_total: '=SUMIFS(J4:J58, A4:A58, "소계", E4:E58, "1차변경")',
    contract_equipment_unit: '=SUMIFS(K4:K58, A4:A58, "소계", E4:E58, "1차변경")',
    contract_equipment_total: '=SUMIFS(L4:L58, A4:A58, "소계", E4:E58, "1차변경")',
    contract_total_unit: '=SUMIFS(M4:M58, A4:A58, "소계", E4:E58, "1차변경")',
    contract_total_total: '=SUMIFS(N4:N58, A4:A58, "소계", E4:E58, "1차변경")',
    plan_quantity: '=SUMIFS(O4:O58, A4:A58, "소계", E4:E58, "1차변경")',
    plan_material_unit: '=SUMIFS(P4:P58, A4:A58, "소계", E4:E58, "1차변경")',
    plan_material_total: '=SUMIFS(Q4:Q58, A4:A58, "소계", E4:E58, "1차변경")',
    plan_labor_unit: '=SUMIFS(R4:R58, A4:A58, "소계", E4:E58, "1차변경")',
    plan_labor_total: '=SUMIFS(S4:S58, A4:A58, "소계", E4:E58, "1차변경")',
    plan_equipment_unit: '=SUMIFS(T4:T58, A4:A58, "소계", E4:E58, "1차변경")',
    plan_equipment_total: '=SUMIFS(U4:U58, A4:A58, "소계", E4:E58, "1차변경")',
    plan_total_unit: '=SUMIFS(V4:V58, A4:A58, "소계", E4:E58, "1차변경")',
    plan_total_total: '=SUMIFS(W4:W58, A4:A58, "소계", E4:E58, "1차변경")',
    execution_quantity: '=SUMIFS(X4:X58, A4:A58, "소계", E4:E58, "1차변경")',
    execution_material_unit: '=SUMIFS(Y4:Y58, A4:A58, "소계", E4:E58, "1차변경")',
    execution_material_total: '=SUMIFS(Z4:Z58, A4:A58, "소계", E4:E58, "1차변경")',
    execution_labor_unit: '=SUMIFS(AA4:AA58, A4:A58, "소계", E4:E58, "1차변경")',
    execution_labor_total: '=SUMIFS(AB4:AB58, A4:A58, "소계", E4:E58, "1차변경")',
    execution_equipment_unit: '=SUMIFS(AC4:AC58, A4:A58, "소계", E4:E58, "1차변경")',
    execution_equipment_total: '=SUMIFS(AD4:AD58, A4:A58, "소계", E4:E58, "1차변경")',
    execution_total_unit: '=SUMIFS(AE4:AE58, A4:A58, "소계", E4:E58, "1차변경")',
    execution_total_total: '=SUMIFS(AF4:AF58, A4:A58, "소계", E4:E58, "1차변경")',
    adjustment_quantity: '=SUMIFS(AG4:AG58, A4:A58, "소계", E4:E58, "1차변경")',
    adjustment_material_unit: '=SUMIFS(AH4:AH58, A4:A58, "소계", E4:E58, "1차변경")',
    adjustment_material_total: '=SUMIFS(AI4:AI58, A4:A58, "소계", E4:E58, "1차변경")',
    adjustment_labor_unit: '=SUMIFS(AJ4:AJ58, A4:A58, "소계", E4:E58, "1차변경")',
    adjustment_labor_total: '=SUMIFS(AK4:AK58, A4:A58, "소계", E4:E58, "1차변경")',
    adjustment_equipment_unit: '=SUMIFS(AL4:AL58, A4:A58, "소계", E4:E58, "1차변경")',
    adjustment_equipment_total: '=SUMIFS(AM4:AM58, A4:A58, "소계", E4:E58, "1차변경")',
    adjustment_total_unit: '=SUMIFS(AN4:AN58, A4:A58, "소계", E4:E58, "1차변경")',
    adjustment_total_total: '=SUMIFS(AO4:AO58, A4:A58, "소계", E4:E58, "1차변경")',
  },
];

var data = [
  {
    category: '세부공종',
    item: '품목',
    specification: '규격',
    unit: '단위',
    revision: '변경 차수',
    contract_quantity: '도급내역',
    plan_quantity: '실행예정',
    execution_quantity: '시행내역',
    adjustment_quantity: '정산내역',
    remark: '비고',
  },
  {
    contract_quantity: '수량',
    contract_material_unit: '직접재료비',
    contract_labor_unit: '직접노무비',
    contract_equipment_unit: '기계경비',
    contract_total_unit: '합계',
    plan_quantity: '수량',
    plan_material_unit: '직접재료비',
    plan_labor_unit: '직접노무비',
    plan_equipment_unit: '기계경비',
    plan_total_unit: '합계',
    execution_quantity: '수량',
    execution_material_unit: '직접재료비',
    execution_labor_unit: '직접노무비',
    execution_equipment_unit: '기계경비',
    execution_total_unit: '합계',
    adjustment_quantity: '수량',
    adjustment_material_unit: '직접재료비',
    adjustment_labor_unit: '직접노무비',
    adjustment_equipment_unit: '기계경비',
    adjustment_total_unit: '합계',
  },
  {
    contract_material_unit: '단가',
    contract_material_total: '금액',
    contract_labor_unit: '단가',
    contract_labor_total: '금액',
    contract_equipment_unit: '단가',
    contract_equipment_total: '금액',
    contract_total_unit: '단가',
    contract_total_total: '금액',
    plan_material_unit: '단가',
    plan_material_total: '금액',
    plan_labor_unit: '단가',
    plan_labor_total: '금액',
    plan_equipment_unit: '단가',
    plan_equipment_total: '금액',
    plan_total_unit: '단가',
    plan_total_total: '금액',
    execution_material_unit: '단가',
    execution_material_total: '금액',
    execution_labor_unit: '단가',
    execution_labor_total: '금액',
    execution_equipment_unit: '단가',
    execution_equipment_total: '금액',
    execution_total_unit: '단가',
    execution_total_total: '금액',
    adjustment_material_unit: '단가',
    adjustment_material_total: '금액',
    adjustment_labor_unit: '단가',
    adjustment_labor_total: '금액',
    adjustment_equipment_unit: '단가',
    adjustment_equipment_total: '금액',
    adjustment_total_unit: '단가',
    adjustment_total_total: '금액',
  },
];

var mergeCells = {
  A1: [1, 3],
  B1: [1, 3],
  C1: [1, 3],
  D1: [1, 3],
  E1: [1, 3],
  F1: [9, 1],
  O1: [9, 1],
  X1: [9, 1],
  AG1: [9, 1],
  AP1: [1, 3],

  F2: [1, 2],
  G2: [2, 1],
  I2: [2, 1],
  K2: [2, 1],
  M2: [2, 1],

  O2: [1, 2],
  P2: [2, 1],
  R2: [2, 1],
  T2: [2, 1],
  V2: [2, 1],

  X2: [1, 2],
  Y2: [2, 1],
  AA2: [2, 1],
  AC2: [2, 1],
  AE2: [2, 1],

  AG2: [1, 2],
  AH2: [2, 1],
  AJ2: [2, 1],
  AL2: [2, 1],
  AN2: [2, 1],
};

var cells = {};

const columns = [];
const startCharCode = 'A'.charCodeAt(0);

// Single letters (A to Z)
for (let i = 0; i < 26; i++) {
  columns.push(String.fromCharCode(startCharCode + i));
}

// Double letters (AA to AP)
for (let i = 0; i < 26; i++) {
  for (let j = 0; j < 26; j++) {
    const letter = String.fromCharCode(startCharCode + i) + String.fromCharCode(startCharCode + j);
    columns.push(letter);
    if (letter === 'AP') break;
  }
  if (columns[columns.length - 1] === 'AP') break;
}

for (let row = 1; row <= 3; row++) {
  columns.forEach(col => {
    cells[`${col}${row}`] = { readonly: true };
  });
}

const columns_total = ['H', 'J', 'L', 'Q', 'S', 'U', 'Z', 'AB', 'AD', 'AI', 'AK', 'AM'];
const columns_total_col = [
  ['F', 'G'],
  ['F', 'I'],
  ['F', 'K'],
  ['O', 'P'],
  ['O', 'R'],
  ['O', 'T'],
  ['X', 'Y'],
  ['X', 'AA'],
  ['X', 'AC'],
  ['AG', 'AH'],
  ['AG', 'AJ'],
  ['AG', 'AL'],
];
const columns_total_unit = ['M', 'V', 'AE', 'AN'];
const columns_total_unit_col = [
  ['G', 'I', 'K'],
  ['P', 'R', 'T'],
  ['Y', 'AA', 'AC'],
  ['AH', 'AJ', 'AL'],
];
const columns_total_total = ['N', 'W', 'AF', 'AO'];
const columns_total_total_col = [
  ['H', 'J', 'L'],
  ['Q', 'S', 'U'],
  ['Z', 'AB', 'AD'],
  ['AI', 'AK', 'AM'],
];
